version: '2'
services:
    backoffice-app:
        image: backoffice
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://backoffice-postgresql:5432/backoffice
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    backoffice-postgresql:
        extends:
            file: postgresql.yml
            service: backoffice-postgresql
